# Generated by Django 3.2.8 on 2021-10-30 06:51

import article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to=article.models.article_directory_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.CharField(max_length=300, null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date'),
        ),
    ]
