# Generated by Django 3.2.8 on 2021-10-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
    ]
