# Generated by Django 3.2.8 on 2021-10-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_about_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='email',
            field=models.EmailField(error_messages={'required': 'Error! Enter your email with @!'}, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='about',
            name='first_name',
            field=models.CharField(error_messages={'required': 'Error! Enter your name!'}, max_length=50, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='about',
            name='last_name',
            field=models.CharField(error_messages={'required': 'Error! Enter your surname!'}, max_length=100, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='about',
            name='message',
            field=models.CharField(error_messages={'required': 'Error! Comment length should not exceed 300 characters!'}, max_length=300, verbose_name='message'),
        ),
    ]
