# Generated by Django 3.2.8 on 2021-11-12 18:19

from django.db import migrations, models
import django.db.models.deletion
import user.managers
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('middle_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('password', models.CharField(max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('username', models.EmailField(max_length=70, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False, help_text='admin')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=user.models.avatar_directory_path)),
                ('personal_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.personalinfo')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', user.managers.UserManager()),
            ],
        ),
    ]
