# Generated by Django 3.2.8 on 2021-11-02 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20211030_1251'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('comment_text', models.CharField(max_length=300, verbose_name='Comment')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='article.article')),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
